### ISSUE TITLE
Fix automatic build

### ISSUE THREAD

**Issue by foosel** [OctoPrint/OctoPrint-FirmwareCheck#2]
Build currently fails in pre-commit black stage due to incompatibility between old black version and latest Click. Either pin version:

```yaml
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: ["--config", "black.toml"]
        additional_dependencies:
          - click==8.0.4
```

or update black.
